Gite API backup file - Backup from original file on virtual machine. - Needs token from Gitea App to run. - Still debugging... - Creates useres, repos, branches, forks and pull request events. - Does not support "[BOT]" on user names. - TODO: fix AttributeError: 'str' object has no attribute 'get'.   - Error after removing "[BOT]" from names.